#!/bin/bash
set -e

BASE_URL="https://raw.githubusercontent.com/linger020/begins/main"
LOG_FILE="/var/log/begins.log"

need_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "请使用 root 执行"
    exit 1
  fi
}

pause() {
  echo
  read -r -p "按 Enter 返回菜单..." _
}

run_remote_script() {
  local url="$1"
  local tmp_file
  tmp_file="$(mktemp)"

  curl -fsSL -H 'Cache-Control: no-cache' -o "$tmp_file" "$url"
  bash "$tmp_file"
  rm -f "$tmp_file"
}

show_status() {
  echo "公网 IPv4: $(curl -4 -fsS --max-time 5 https://ip.sb 2>/dev/null || echo unknown)"
  echo "Hostname: $(hostname 2>/dev/null || echo unknown)"
  timedatectl 2>/dev/null | grep "Time zone" || true
  echo "TCP 拥塞控制: $(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  echo "当前文件句柄: $(ulimit -n 2>/dev/null || echo unknown)"
  echo
  df -h
  echo
  free -h
}

load_debian_os_info() {
  if [ ! -r /etc/os-release ]; then
    echo "无法读取 /etc/os-release"
    exit 1
  fi

  # shellcheck disable=SC1091
  . /etc/os-release

  if [ "${ID:-}" != "debian" ]; then
    echo "当前系统不是 Debian：${PRETTY_NAME:-unknown}"
    exit 1
  fi

  DEBIAN_PRETTY_NAME="${PRETTY_NAME:-Debian}"
  DEBIAN_CODENAME="${VERSION_CODENAME:-}"
  if [ -z "$DEBIAN_CODENAME" ] && command -v lsb_release >/dev/null 2>&1; then
    DEBIAN_CODENAME="$(lsb_release -sc 2>/dev/null || true)"
  fi

  if [ -z "$DEBIAN_CODENAME" ]; then
    echo "无法识别 Debian 版本代号"
    exit 1
  fi
}

debian_source_components() {
  case "$DEBIAN_CODENAME" in
    bookworm|trixie|forky|duke)
      echo "main contrib non-free non-free-firmware"
      ;;
    *)
      echo "main contrib non-free"
      ;;
  esac
}

backup_debian_sources() {
  local backup_dir
  backup_dir="/root/apt-sources-backup-$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$backup_dir/sources.list.d"

  if [ -f /etc/apt/sources.list ]; then
    cp -a /etc/apt/sources.list "$backup_dir/sources.list"
  fi

  shopt -s nullglob
  for file in /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
    if grep -Eqi '(deb\.debian\.org|security\.debian\.org|ftp\.[a-z0-9.-]+\.debian\.org|debian-security|/debian[[:space:]/])' "$file"; then
      mv "$file" "$backup_dir/sources.list.d/"
    fi
  done
  shopt -u nullglob

  echo "已备份旧 Debian 源到：$backup_dir"
}

write_debian_official_sources() {
  local components
  components="$(debian_source_components)"

  cat > /etc/apt/sources.list <<EOF
# Debian official repositories generated by begins
# Codename: $DEBIAN_CODENAME

deb http://deb.debian.org/debian $DEBIAN_CODENAME $components
deb http://deb.debian.org/debian $DEBIAN_CODENAME-updates $components
deb http://security.debian.org/debian-security $DEBIAN_CODENAME-security $components
deb http://deb.debian.org/debian $DEBIAN_CODENAME-backports $components
EOF

  chmod 0644 /etc/apt/sources.list
}

run_debian_official_source() {
  load_debian_os_info

  echo "当前系统：$DEBIAN_PRETTY_NAME"
  echo "版本代号：$DEBIAN_CODENAME"
  echo "将切换为 Debian 官方源：deb.debian.org / security.debian.org"
  echo

  backup_debian_sources
  write_debian_official_sources

  echo
  echo "新的 /etc/apt/sources.list："
  cat /etc/apt/sources.list
  echo

  apt-get clean
  apt-get update

  echo
  echo "Debian 官方源切换完成。"
}

set_timezone_by_ip() {
  apt update >/dev/null 2>&1 || true
  apt install -y curl ca-certificates >/dev/null 2>&1 || true
  TZ_NAME="$(curl -4 -fsS --max-time 8 https://ipapi.co/timezone 2>/dev/null || true)"
  if [ -n "$TZ_NAME" ] && timedatectl list-timezones | grep -qx "$TZ_NAME"; then
    timedatectl set-timezone "$TZ_NAME"
    echo "已设置时区：$TZ_NAME"
  else
    timedatectl set-timezone America/Los_Angeles || true
    echo "识别失败，已回退到 America/Los_Angeles"
  fi
  timedatectl
}

set_timezone_los_angeles() {
  timedatectl set-timezone America/Los_Angeles || {
    echo "设置洛杉矶时区失败"
    return 1
  }

  echo "已设置时区为 America/Los_Angeles"
  timedatectl
}

install_speedtest() {
  run_remote_script "https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh"
  apt update
  apt install -y speedtest
}

ensure_speedtest_installed() {
  if command -v speedtest >/dev/null 2>&1; then
    return 0
  fi

  echo "未检测到 speedtest，正在自动安装..."
  install_speedtest || {
    echo "Speedtest 安装失败"
    return 1
  }

  if ! command -v speedtest >/dev/null 2>&1; then
    echo "Speedtest 安装后仍未检测到 speedtest 命令"
    return 1
  fi
}

run_speedtest() {
  ensure_speedtest_installed || return 1

  echo "开始运行 Speedtest..."
  speedtest
}

run_backtrace() {
  if ! command -v backtrace >/dev/null 2>&1; then
    echo "未检测到 backtrace，先安装。"
    run_remote_script "https://raw.githubusercontent.com/zhanghanyun/backtrace/main/install.sh"
  fi
  backtrace
}

run_xuicert() {
  run_remote_script "$BASE_URL/certbot-xuicert.sh"
}

run_universal_system_full_tune() {
  run_remote_script "$BASE_URL/begins/system-full-tune.sh"
}

run_install_bbr_v3() {
  run_remote_script "$BASE_URL/begins/install-bbr-v3.sh"
}

print_install_command() {
  echo "重新安装 begins："
  echo "curl -fsSL -H 'Cache-Control: no-cache' -o /usr/local/bin/begins https://raw.githubusercontent.com/linger020/begins/main/begins.sh && chmod +x /usr/local/bin/begins && begins"
}

uninstall_begins() {
  rm -f /usr/local/bin/begins
  echo "begins 已卸载。"
  echo
  print_install_command
  exit 0
}

self_update_begins() {
  local url
  url="$BASE_URL/begins.sh?ts=$(date +%s)"

  curl -fsSL -H 'Cache-Control: no-cache' -o /usr/local/bin/begins "$url"
  chmod +x /usr/local/bin/begins
  echo "begins 已更新，正在重新加载新菜单..."
  exec /usr/local/bin/begins
}

show_menu() {
  clear
  echo "╔────────────────────────────────────────────────╗"
  echo "│   Begins Server Management Script              │"
  echo "│   0. Exit Script                               │"
  echo "│────────────────────────────────────────────────│"
  echo "│   基础初始化                                   │"
  echo "│   1. Debian 初始化 + 常用包 + certbot          │"
  echo "│      REALITY 友好，不装 nginx/ufw/fail2ban     │"
  echo "│   2. 切换为 Debian 官方源                      │"
  echo "│   3. 修改 hostname 为公网 IP + 红色提示符      │"
  echo "│   4. 根据公网 IP 设置时区                      │"
  echo "│   5. 设置时区为美国洛杉矶                      │"
  echo "│────────────────────────────────────────────────│"
  echo "│   系统优化 / 内核                              │"
  echo "│   6. 通用系统暴力优化（高并发/TCP/IO/Limit）  │"
  echo "│   7. 安装最新 BBR v3（byJoey/Actions-bbr-v3） │"
  echo "│────────────────────────────────────────────────│"
  echo "│   证书工具                                     │"
  echo "│   8. 单独安装 certbot                          │"
  echo "│   9. 申请证书并软链接到 /root/xuicert          │"
  echo "│────────────────────────────────────────────────│"
  echo "│   网络测试                                     │"
  echo "│  10. 运行 Speedtest                            │"
  echo "│  11. 测试网络回程                              │"
  echo "│────────────────────────────────────────────────│"
  echo "│   系统查看                                     │"
  echo "│  12. 查看监听端口                              │"
  echo "│  13. 查看系统状态                              │"
  echo "│  14. 查看 begins 日志                          │"
  echo "│────────────────────────────────────────────────│"
  echo "│   管理                                         │"
  echo "│  15. 更新 begins                               │"
  echo "│  16. 卸载 begins                               │"
  echo "╚────────────────────────────────────────────────╝"
  echo
  echo "Reality mode: nginx not installed by default, 443 reserved"
  echo
}

need_root
mkdir -p "$(dirname "$LOG_FILE")"
touch "$LOG_FILE"

while true; do
  show_menu
  read -r -p "Please enter your selection [0-16]: " choice
  case "$choice" in
    0) exit 0 ;;
    1) run_remote_script "$BASE_URL/init-server.sh"; pause ;;
    2) run_debian_official_source; pause ;;
    3) run_remote_script "$BASE_URL/host-ip.sh"; pause ;;
    4) set_timezone_by_ip; pause ;;
    5) set_timezone_los_angeles; pause ;;
    6) run_universal_system_full_tune; pause ;;
    7) run_install_bbr_v3; pause ;;
    8) apt update && apt install -y certbot; pause ;;
    9) run_xuicert; pause ;;
    10) run_speedtest; pause ;;
    11) run_backtrace; pause ;;
    12) ss -tlnp; pause ;;
    13) show_status; pause ;;
    14) tail -n 120 "$LOG_FILE" 2>/dev/null || true; pause ;;
    15) self_update_begins ;;
    16) uninstall_begins ;;
    *) echo "[ERR] Please enter the correct number [0-16]"; sleep 1 ;;
  esac
done
