#!/bin/bash
set -euo pipefail

need_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "请使用 root 执行"
    exit 1
  fi
}

load_os_info() {
  if [ ! -r /etc/os-release ]; then
    echo "无法读取 /etc/os-release"
    exit 1
  fi

  # shellcheck disable=SC1091
  . /etc/os-release

  if [ "${ID:-}" != "debian" ]; then
    echo "当前系统不是 Debian：${PRETTY_NAME:-unknown}"
    exit 1
  fi

  CODENAME="${VERSION_CODENAME:-}"
  if [ -z "$CODENAME" ] && command -v lsb_release >/dev/null 2>&1; then
    CODENAME="$(lsb_release -sc 2>/dev/null || true)"
  fi

  if [ -z "$CODENAME" ]; then
    echo "无法识别 Debian 版本代号"
    exit 1
  fi
}

components_for_codename() {
  case "$CODENAME" in
    bookworm|trixie|forky|duke)
      echo "main contrib non-free non-free-firmware"
      ;;
    *)
      echo "main contrib non-free"
      ;;
  esac
}

backup_existing_sources() {
  BACKUP_DIR="/root/apt-sources-backup-$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$BACKUP_DIR/sources.list.d"

  if [ -f /etc/apt/sources.list ]; then
    cp -a /etc/apt/sources.list "$BACKUP_DIR/sources.list"
  fi

  shopt -s nullglob
  for file in /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
    if grep -Eqi '(deb\.debian\.org|security\.debian\.org|ftp\.[a-z0-9.-]+\.debian\.org|debian-security|/debian[[:space:]/])' "$file"; then
      mv "$file" "$BACKUP_DIR/sources.list.d/"
    fi
  done
  shopt -u nullglob

  echo "已备份旧 Debian 源到：$BACKUP_DIR"
}

write_official_sources() {
  local components
  components="$(components_for_codename)"

  cat > /etc/apt/sources.list <<EOF
# Debian official repositories generated by begins
# Codename: $CODENAME

deb http://deb.debian.org/debian $CODENAME $components
deb http://deb.debian.org/debian $CODENAME-updates $components
deb http://security.debian.org/debian-security $CODENAME-security $components
deb http://deb.debian.org/debian $CODENAME-backports $components
EOF

  chmod 0644 /etc/apt/sources.list
}

main() {
  need_root
  load_os_info

  echo "当前系统：${PRETTY_NAME:-Debian}"
  echo "版本代号：$CODENAME"
  echo "将切换为 Debian 官方源：deb.debian.org / security.debian.org"
  echo

  backup_existing_sources
  write_official_sources

  echo
  echo "新的 /etc/apt/sources.list："
  cat /etc/apt/sources.list
  echo

  apt-get clean
  apt-get update

  echo
  echo "Debian 官方源切换完成。"
}

main "$@"
